export const planetsData = [
        {
            name: "Mercury",
            size: 1,
            dist: 20,
            speed: 0.009,
            spin: 0.002,
            textures: [
                "textures/2k_mercury.jpg",
                "textures/mercurymap.jpg",
                "textures/2k_mercury.jpg",
            ],
            color: 0x8c7853,
            info: {
                type: "Terrestrial Planet",
                diameter: "4,879 km",
                mass: "3.3 × 10^23 kg",
                distanceFromSun: "57.9 million km",
                orbitalPeriod: "88 days",
                temperature: "-173°C to 427°C",
                moons: "0",
                description: "Mercury is the smallest and closest planet to the Sun.",
            },
        },
        {
            name: "Venus",
            size: 1.5,
            dist: 28,
            speed: 0.008,
            spin: 0.001,
            textures: [
                "textures/2k_venus_atmosphere.jpg",
                "textures/venusmapthumb.jpg",
                "textures/2k_venus_atmosphere.jpg",
            ],
            color: 0xe39e54,
            info: {
                type: "Terrestrial Planet",
                diameter: "12,104 km",
                mass: "4.87 × 10^24 kg",
                distanceFromSun: "108.2 million km",
                orbitalPeriod: "225 days",
                temperature: "462°C",
                moons: "0",
                description:
                    "Venus is the second planet from the Sun, known for its extreme greenhouse effect.",
            },
        },
        {
            name: "Earth",
            size: 2,
            dist: 38,
            speed: 0.007,
            spin: 0.02,
            textures: [
                "textures/earth_atmos_2048.jpg",
                "textures/2k_earth_1.jpg",
                "textures/earthcloudmap.jpg",
            ],
            color: 0x6b93d6,
            info: {
                type: "Terrestrial Planet",
                diameter: "12,742 km",
                mass: "5.97 × 10^24 kg",
                distanceFromSun: "149.6 million km",
                orbitalPeriod: "365.25 days",
                temperature: "-88°C to 58°C",
                moons: "1 (Moon)",
                description:
                    "Earth is the third planet from the Sun and the only known planet with life.",
            },
        },
        {
            name: "Mars",
            size: 1.5,
            dist: 48,
            speed: 0.006,
            spin: 0.018,
            textures: [
                "textures/2k_mars.jpg",
                "textures/mars_thumbnail.jpg",
                "textures/marsmapthumb.jpg",
            ],
            color: 0xcd5c5c,
            info: {
                type: "Terrestrial Planet",
                diameter: "6,779 km",
                mass: "6.42 × 10^23 kg",
                distanceFromSun: "227.9 million km",
                orbitalPeriod: "687 days",
                temperature: "-87°C to -5°C",
                moons: "2 (Phobos, Deimos)",
                description: "Mars is the fourth planet, known as the 'Red Planet'.",
            },
        },
        {
            name: "Jupiter",
            size: 4,
            dist: 70,
            speed: 0.005,
            spin: 0.03,
            textures: [
                "textures/2k_jupiter.jpg",
                "textures/jupitermapthumb.jpg",
                "textures/jupiter2colorthumb.jpg",
            ],
            color: 0xd8ca9d,
            info: {
                type: "Gas Giant",
                diameter: "139,820 km",
                mass: "1.90 × 10^27 kg",
                distanceFromSun: "778.5 million km",
                orbitalPeriod: "11.9 years",
                temperature: "-108°C",
                moons: "79+",
                description:
                    "Jupiter is the largest planet in the Solar System, a gas giant.",
            },
        },
        {
            name: "Saturn",
            size: 3.5,
            dist: 90,
            speed: 0.004,
            spin: 0.025,
            textures: [
                "textures/2k_saturn.jpg",
                "textures/saturnmapthumb.jpg",
                "textures/2k_saturn.jpg",
            ],
            color: 0xe3d9b0,
            info: {
                type: "Gas Giant",
                diameter: "116,460 km",
                mass: "5.68 × 10^26 kg",
                distanceFromSun: "1.43 billion km",
                orbitalPeriod: "29.5 years",
                temperature: "-139°C",
                moons: "82+",
                description:
                    "Saturn is the sixth planet, famous for its spectacular ring system.",
            },
        },
        {
            name: "Uranus",
            size: 2.5,
            dist: 115,
            speed: 0.003,
            spin: 0.015,
            textures: [
                "textures/2k_uranus.jpg",
                "textures/uranusmapthumb.jpg",
                "textures/2k_uranus.jpg.jpg",
            ],
            color: 0x4fd0e7,
            info: {
                type: "Ice Giant",
                diameter: "50,724 km",
                mass: "8.68 × 10^25 kg",
                distanceFromSun: "2.87 billion km",
                orbitalPeriod: "84 years",
                temperature: "-197°C",
                moons: "27",
                description: "Uranus is the seventh planet, rotating on its side.",
            },
        },
        {
            name: "Neptune",
            size: 2.3,
            dist: 135,
            speed: 0.002,
            spin: 0.014,
            textures: [
                "textures/2k_neptune.jpg",
                "textures/neptunemapthumb.jpg",
                "textures/2k_neptune.jpg",
            ],
            color: 0x4b70dd,
            info: {
                type: "Ice Giant",
                diameter: "49,244 km",
                mass: "1.02 × 10^26 kg",
                distanceFromSun: "4.5 billion km",
                orbitalPeriod: "165 years",
                temperature: "-201°C",
                moons: "14",
                description:
                    "Neptune is the eighth and farthest known planet from the Sun.",
            },
        },
    ];